title: hintbw's Home on the Web
description: My personal blog, with a focus on technology and engineering topics with the occasional tangent to other topics
permalink: /:slugified_categories/:title/

date_format: "%b %-d, %Y"

exclude:
  - "package*.json"
  - "*.config.js"
  - netlify.toml
  - README.md
  - LICENSE
  - Makefile
